config/routes.rb
Rails.application.routes.draw do

  root 'sample_app#home'

  get 'users/new'
  get 'home'    => 'sample_app#home'
  get 'help'    => 'sample_app#help'
  get 'about'   => 'sample_app#about'
  get 'contact' => 'sample_app#contact'
  get 'login' => 'sample_app#login'
  get 'signup'  => 'users#new'

  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base	 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sample_app_controller.rb
class SampleAppController < ApplicationController
	
	def home
	end

	def about
	end

	def help
	end
 	
	def contact
	end

	def login
	end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/sample_app_helper.rb
module SampleAppHelper
	def full_title(page_title = '')
		base_title = "Website Layout Example"
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"
		end
	end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
<%= link_to image_tag("rubyonrails.png", alt: "Ruby on Rails logo"),'http://rubyonrails.org/' %>
<hr />
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "sample app", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav pull-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Help",   help_path %></li>            
            <li><%= link_to "Log in", login_path %></li>
          </ul>
        </nav>
      </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all","data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag "icon.png" %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/sample_app/about.html.erb
<% provide(:title,"About") %>
<div class="center jumbotron">
	<h1>Welcome to the About Sanple App</h1>
	<h2>
		Rails Tutorial : <a href="http://www.railstutorial.org/"><em>http://www.railstutorial.org/</em></a><br />
		Rails Tutorial Book : <a href="http://www.railstutorial.org/book"><em>http://www.railstutorial.org/book</em></a><br />
		Screencast Series : <a href="http://screencasts.railstutorial.org/"><em>http://screencasts.railstutorial.org/</em></a><br />
		Ruby on Rails : <a href="http://rubyonrails.org/"><em>http://rubyinrails.org/</em></a>
	</h2>
</div>

app/views/sample_app/contact.html.erb
<% provide(:title,"Contact")%>
<div class="center jumbotron">
	<h1>Welcome to the Contact Sample App</h1>
	<h2>You can contact me via email:<a href="https://github.com/namlv">https://github.com/namlv</a></h2>
</div>

app/views/sample_app/help.html.erb
<% provide(:title,"Help") %>
<div class="center jumbotron">
	<h1>Welcome to the Help Sample App</h1>

	<h2>
		Get help on the Ruby on Rails Tutorial at the
		<a href="http://www.railstutorial.org/#help">Rails Tutorial help section</a>.
		To get help on this sample app, see the
		<a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>book</a>.
	</h2>
</div>

app/views/sample_app/home.html.erb
<% provide(:title,"Home") %>
<div class="center jumbotron">
	<h1>Welcome to the Sample App</h1>

	<h2>
		This is the home page for the
		<a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
		sample application.
	</h2>
	<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/sample_app/login.html.erb
<% provide(:title,"Log In") %>
<div class="center jumbotron">
<h1>Welcom to the Login Sample App</h1>
	<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="center jumbotron">
  <h1>Sign up</h1><br />
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Create my account", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="center jumbotron">
	<div class="row">
		<aside class="col-md-4">
			<section class="user_info">
				<h1>
					<%= gravatar_for @user %>
					<%= @user.name %>
				</h1>
			</section>
		</aside>
	</div>
</div>	